version: '3.8'

services:
  language-detection-service:
    container_name: language-detection-service   # <-- fixed short name
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "6011:6011"
    environment:
      - SERVER_ADDRESS=0.0.0.0
      - SERVER_PORT=6011
      - AWS_REGION=${AWS_REGION:-us-east-1}
      - USE_AWS_COMPREHEND=${USE_AWS_COMPREHEND:-true}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID:-}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY:-}
      - MAX_TEXT_LENGTH=${MAX_TEXT_LENGTH:-5000}
      - MIN_CONFIDENCE_THRESHOLD=${MIN_CONFIDENCE_THRESHOLD:-0.1}
      - SERVICE_VERSION=${SERVICE_VERSION:-1.0.0}
      - MODEL_VERSION=${MODEL_VERSION:-1.0.0}
      - SHUTDOWN_TIMEOUT_SECONDS=${SHUTDOWN_TIMEOUT_SECONDS:-30}
    restart: unless-stopped
